FROM node:13.10.1-stretch as build
  
WORKDIR /src/

RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get clean \
 && echo 'Finished installing dependencies'

COPY package*.json ./

RUN npm i --production

FROM node:13.10.1-slim as production
  
WORKDIR /src/

RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get clean \
 && echo 'Finished installing dependencies'

COPY --from=build /src/node_modules node_modules
COPY . .

ENV NODE_ENV production
ENV PORT 3000
EXPOSE 3000

USER node

CMD ["npm", "start"]