version: '3.3'

services:
    web:
        build:
            context: ./
            dockerfile: ./Dockerfile-production
            args:
                http_proxy: ${npm_config_proxy}
        environment: 
            PORT: 3000
            HOST: '0.0.0.0'
        ports:
            - 3000:3000
        restart: always